### ISSUE TITLE
It seem the result of this library is not the same with github trending result for monthy.

### ISSUE THREAD

**Issue by honeytidy** [hedyhli/gtrending#32] opened 2021-08-30 11:27 UTC
Here is the result of this library for monthly trending:
```
benyaminahmed/nft-image-generator
nextcloud/server
AkashSingh3031/The-Complete-FAANG-Preparation
benbusby/whoogle-search
lite-xl/lite-xl
whyour/qinglong
Chia-Network/chia-blockchain
myspaghetti/macos-virtualbox
EbookFoundation/free-programming-books
CyberPunkMetalHead/binance-trading-bot-new-coins
AhmadRafiee/Docker_training_with_DockerMe
Rapptz/discord.py
HashLips/generative-art-node
PeterL1n/RobustVideoMatting
hecrj/iced
bregman-arie/devops-exercises
laurent22/joplin
binance-chain/bsc
microsoft/Web-Dev-For-Beginners
meilisearch/MeiliSearch
kilimchoi/engineering-blogs
kunal-kushwaha/DSA-Bootcamp-Java
jina-ai/jina
blueedgetechno/windows11
tdlib/td
```
and here is the result of [github trending](https://github.com/trending?since=monthly):
```
 yt-dlp / yt-dlp
A youtube-dl fork with additional features and fixes

Python  5,234  302 Built by @dstftw @phihag @remitamine @jaimeMF @yan12125 4,082 stars this month
 NvChad / NvChad
An attempt to make neovim cli as functional as an IDE while being very beautiful , blazing fast.

Lua  6,061  294 Built by @siduck76 @Akianonymus @ashincoder @Vanderscycle @G-Rowell 3,350 stars this month
 dataease / dataease
人人可用的开源数据可视化分析工具。

Java  3,031  422 Built by @XiaJunjie2020 @ziyujiahao @fit2cloud-chenyw @jinlong-T @tjlygdx 1,995 stars this month
 fuzhengwei / small-spring
🌱《 Spring 手撸专栏》，本专栏以 Spring 源码学习为目的，通过手写简化版 Spring 框架，了解 Spring 核心原理。在手写的过程中会简化 Spring 源码，摘取整体框架中的核心逻辑，简化代码实现过程，保留核心功能，例如：IOC、AOP、Bean生命周期、上下文、作用域、资源处理等内容实现。

Java  1,786  373 Built by @fuzhengwei 1,184 stars this month
 willmcgugan / textual
Textual is a TUI (Text User Interface) framework for Python inspired by modern web development.

Python  4,149  87 Built by @willmcgugan @falkben @EdwardBetts @erezsh @lllama 2,758 stars this month
 geekxh / hello-algorithm
🌍 针对小白的算法训练 | 包括四部分：①.算法基础 ②.力扣图解 ③.大厂面经 ④.CS_汇总 | 附：1、千本开源电子书 2、百张技术思维导图（项目花了上百小时，希望可以点 star 支持，🌹感谢~）

Java  28,239  5,406 Built by @geekxh @kangkang0801 @dependabot @rookieInn @ixysoft 1,272 stars this month
 papers-we-love / papers-we-love
Papers from the computer science community to read and discuss.

Shell  48,940  4,192 Built by @zeeshanlakhani @DarrenN @jeremyheiler @newsomc @bowmanb 2,272 stars this month
 DIGITALCRIMINAL / OnlyFans
Scrape all the media from an OnlyFans account - Updated regularly

Python  2,487  342 Built by @DIGITALCRIMINAL @aboredpervert @ecchiecchi0 @helopy @banillasolt 650 stars this month
 google / zx
A tool for writing better scripts

JavaScript  21,703  407 Built by @antonmedv @antongolub @thescientist13 @matt-fidd @fioriandrea 3,520 stars this month
 commaai / openpilot
openpilot is an open source driver assistance system. openpilot performs the functions of Automated Lane Centering and Adaptive Cruise Control for over 100 supported car makes and models.

C++  29,560  5,465 Built by @adeebshihadeh @pd0wm @deanlee @HaraldSchafer @geohot 3,570 stars this month
 JetBrains / compose-jb
Jetpack Compose for Desktop and Web, a modern UI framework for Kotlin that makes building performant and beautiful user interfaces easy and enjoyable.

Kotlin  6,050  333 Built by @Schahen @igordmn @olonho @AlexeyTsvetkov @Rsedaikin 1,080 stars this month
 tauri-apps / tauri
Build smaller, faster, and more secure desktop applications with a web frontend.

Rust  21,711  491 Built by @lucasfernog @renovate @jbolda @nothingismagick @tensor-programming 2,935 stars this month
 spring-projects / spring-authorization-server
The Spring Authorization Server project is focused on delivering OAuth 2.1 Authorization Server support to the Spring community.

Java  2,583  464 Built by @jgrandja @sjohnr @Kehrlann @rwinch @anoopgarlapati 430 stars this month
 SJang1 / korea-covid-19-remaining-vaccine-macro
잔여백신 조회 및 예약 매크로

Python  723  297 Built by @SJang1 @MPThLee @Queue-ri @sh-cho @teslamint 479 stars this month
 mitmproxy / mitmproxy
An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.

Python  24,454  3,034 Built by @mhils @cortesi @Kriechi @dufferzafar @MatthewShao 1,415 stars this month
 Qv2ray / Qv2ray
⭐ Linux / Windows / macOS 跨平台 V2Ray 客户端 | 支持 VMess / VLESS / SSR / Trojan / Trojan-Go / NaiveProxy / HTTP / HTTPS / SOCKS5 | 使用 C++ / Qt 开发 | 可拓展插件式设计 ⭐

C++  12,311  2,205 Built by @lhy0403 @DuckSoft @ymshenyu @darsvador @aliyuchang33 969 stars this month
 RustPython / RustPython
A Python Interpreter written in Rust

Python  8,972  581 Built by @coolreader18 @youknowone @windelbouwman @palaviv @fanninpm 1,083 stars this month
 basarat / typescript-book
📚 The definitive guide to TypeScript and possibly the best TypeScript book 📖. Free and Open Source 🌹

TypeScript  15,482  1,948 Built by @basarat @Marketionist @djyde @dwillmer @timkraut 1,352 stars this month
 swc-project / swc
swc is a super-fast compiler written in rust; producing widely-supported javascript from modern standards and typescript.

TypeScript  14,686  403 Built by @kdy1 @dsherret @Brooooooklyn @bors @devongovett 1,809 stars this month
 timlrx / tailwind-nextjs-starter-blog
This is a Next.js, Tailwind CSS blogging starter template. Comes out of the box configured with the latest technologies to make technical writing a breeze. Easily configurable and customizable. Perfect as a replacement to existing Jekyll and Hugo individual blogs.

JavaScript  1,090  255 Built by @timlrx @Music47ell @DoctorDerek @DLevai94 @aloisdg 488 stars this month
 datafuselabs / datafuse
An elastic and scalable Cloud Warehouse, offers Blazing Fast Query and combines Elasticity, Simplicity, Low cost of the Cloud, built to make the Data Cloud easy

Rust  1,959  164 Built by @BohuTANG @sundy-li @datafuse-bot @zhang2014 @jyizheng 1,027 stars this month
 deepmind / deepmind-research
This repository contains implementations and illustrative code to accompany DeepMind publications

Jupyter Notebook  7,878  1,501 Built by @derpson @Augustin-Zidek @alimuldal @diegolascasas @alvarosg 621 stars this month
 mxrch / GHunt
🕵️‍♂️ Investigate Google emails and documents.

Python  10,086  788 Built by @mxrch @NikolozCh @PinkDev1 @christianboyle @outime 503 stars this month
 emilk / egui
egui: an easy-to-use immediate mode GUI in pure Rust

Rust  4,755  215 Built by @emilk @EmbersArc @parasyte @optozorax @follower 1,217 stars this month
 filebrowser / filebrowser
```
it seems monthly and weely reslut all the same with daily? Is this a bug or something i use it with a wrong way?

**Comment by hedyhli** [comment] 2021-09-01 05:29
Hi! Thank you for opening this issue. It seems that it was caused by a typo (in 16b7605b) and it should be fixed now.

**Closed by hedyhli** 2021-09-01 05:29 UTC
